default['mongodb']['config']['rest']="false"
default['mongodb']['config']['bind_ip']="0.0.0.0"
default['mongodb']['config']['port']="27017"
default['mongodb']['config']['dbpath'] = "/data/mongodb"
default['mongodb']['config']['logpath'] = "/data/log/mongodb/mongodb.log"
